name: CI

on: [push]

jobs:

  lint:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - uses: pre-commit/action@v3.0.1

  test:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        python-version: ['3.12', '3.13']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: python -m pip install -U uv
    - name: Run tests
      run: python -m uv run -m pytest

  deploy:
    needs: test
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Build dists
      run: |
        python -m pip install wheel build
        python -m build
    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
